language: node_js

node_js:
    - stable

sudo: false

before_script:
    - npm install -g grunt-cli

script:
    - npm test
    - grunt

after_success:
    - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'
    - sh script/deploy

deploy:
    provider: npm
    email: "rrdelaney@outlook.com"
    api_key: $NPM_TOKEN
    skip_cleanup: true
    on:
        branch: master
        condition: $(npm view jadelint dist-tags.latest) != $(node -p "require('./package.json').version")
